services:

  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 102030
    networks:
      - app-network

networks:
  app-network:
    driver: bridge